### ISSUE TITLE
File not found QThread, QCache, QDatetime

### ISSUE THREAD

**Issue by fplaten** [ManWithBear/PoBMacOSBuild#1]
Hi!

First of all thank you so much for your effort! 

Unfortunately I get build errors when making the project:

```
pobfrontend@exe/../../pobfrontend/subscript.hpp:4:10: fatal error: 'QThread' file not found
#include <QThread>
```

```
pobfrontend@exe/../../pobfrontend/pobwindow.hpp:1:10: fatal error: 'QCache' file not found
#include <QCache>
```

```
../pobfrontend/main.cpp:3:10: fatal error: 'QDateTime' file not found
#include <QDateTime>
```

Any idea how to fix this? Is this maybe a Catalina issue?

Thanks and best regards,
Florian

**Comment by ManWithBear** [comment]
Hello.
Make sure you have `qt5` installed in system (`make tools` should install it by brew).
Add in your `.zshrc` exports for qt:
```
export PATH="/usr/local/opt/qt/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/qt/lib"
export CPPFLAGS="-I/usr/local/opt/qt/include"
export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
```
`brew`  doesn't add them for some reason.
From now you should be able to compile frontend. You may want to delete `build` folder and run `make frontend` again (or `make clean all`)

**Comment by fplaten** [comment]
It works! I was missing the last import. Thank you so much!
